export const USER_ROLES = {
  ADMIN: 'ADMIN',
  RECEPTIONIST: 'RECEPTIONIST',
  PHARMACIST: 'PHARMACIST',
  GYNAECOLOGIST: 'GYNAECOLOGIST',
};

export const ROLES = [USER_ROLES.ADMIN, USER_ROLES.RECEPTIONIST, USER_ROLES.PHARMACIST, USER_ROLES.GYNAECOLOGIST];
