export const USER_ROLES = {
  DOCTOR: 'DOCTOR',
  RECEPTIONIST: 'RECEPTIONIST',
  PHARMACIST: 'PHARMACIST',
  GYNAECOLOGIST: 'GYNAECOLOGIST',
};

export const ROLES = [
  USER_ROLES.DOCTOR,
  USER_ROLES.RECEPTIONIST,
  USER_ROLES.PHARMACIST,
  USER_ROLES.GYNAECOLOGIST,
];
